openapi: 3.0.1
info:
  title: 'default-endpoint'
  version: 1.0.0
x-wso2-disable-security: true
paths:
  /*:
    get:
      x-wso2-disable-security: true
      responses:
        '200':
          description: Ok
    post:
      x-wso2-disable-security: true
      responses:
        '200':
          description: Ok
